### PR TITLE
Changed the dashboard definition

### PR DESCRIPTION
**Pull request by gsoria**
This is a workaround to solve the problem displaying the PgAdmin4 dashboard.

### CODE REVIEW

**Comment by dpage** [comment]
That works perfectly - thank you!

**Comment by dpage** [comment]
Oops, sorry - I spoke too soon. It displays the login page, but upon login I get:

2886795297-80-frugo04.environments.katacoda.com sent an invalid response.
ERR_INVALID_REDIRECT

On the command line I still see the same issue I reported via email:

(pgadmin4) dpage@hal:~/git/pgadmin4$ wget -S http://2886795316-80-frugo04.environments.katacoda.com
--2019-09-10 14:53:52--  http://2886795316-80-frugo04.environments.katacoda.com/
Resolving 2886795316-80-frugo04.environments.katacoda.com (2886795316-80-frugo04.environments.katacoda.com)... 35.201.124.219
Connecting to 2886795316-80-frugo04.environments.katacoda.com (2886795316-80-frugo04.environments.katacoda.com)|35.201.124.219|:80... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 302 Found
  Server: nginx/1.15.0
  Date: Tue, 10 Sep 2019 18:53:53 GMT
  Content-Type: text/html; charset=utf-8
  Content-Length: 341
  Location: https:///login?next=%2F%2F2886795316-80-frugo04.environments.katacoda.com%2F
  Set-Cookie: pga4_session=af8391ad-983a-4639-8d6c-bac1ee7d1003!kO92iLyRRdlAhlYiZhRx6oSR/XU=; Expires=Wed, 11-Sep-2019 18:53:53 GMT; HttpOnly; Path=/
  Via: 1.1 google
Location: https:///login?next=%2F%2F2886795316-80-frugo04.environments.katacoda.com%2F [following]
https:///login?next=%2F%2F2886795316-80-frugo04.environments.katacoda.com%2F: Invalid host name.

**Comment by gsoria** [comment]
Thanks :), I'll check the problem with the redirect. I see you are using one custom image in the scenario  https://hub.docker.com/r/dpage/pgadmin4. Could you please point me to the dockerfile corresponding this image?

**Comment by dpage** [comment]
I can, though it's a little complicated:

- I'm using a nightly snapshot build (rather than latest which is v4.12) which allows me to disable enhanced cookie protection, as we've seen cause similar issues to this on Azure.
- The current code in the GIT repo has some environmental requirements as well as a supporting shell script. The container cannot be built purely with the Dockerfile.
- By pure coincidence, I do have a patch in review that does allow building with nothing more than the source code and Dockerfile, but that's not committed yet. You may want to try it though - it would be a lot easier :-).

The current container build code for pgAdmin can be found at https://git.postgresql.org/gitweb/?p=pgadmin4.git;a=tree;f=pkg/docker

You can checkout the pgAdmin code using git from https://git.postgresql.org/git/pgadmin4.git

The patch to simplify the container build process (which can be applied to a checkout of git master) is here: https://www.postgresql.org/message-id/CA%2BOCxoy3ZAKhPcWu1XZrsrT2WdM1uSn%2BfQUhz7kkMgLFTEujOQ%40mail.gmail.com

**Comment by gsoria** [comment]
Thanks @dpage :) The issue seems to be related to how the application (PgAdmin4) performs the redirect after login since version 4.4.

The user login in a URL similar to:
https://2886795280-80-frugo01.environments.katacoda.com/login

And until the version 4.3 after login the application redirects to:
https://2886795280-80-frugo01.environments.katacoda.com/browser/

I tested with these versions and the redirect after login works well:

`docker run -p 80:80 -e "PGADMIN_DEFAULT_EMAIL=user@domain.com" -e "PGADMIN_DEFAULT_PASSWORD=SuperSecret" -d dpage/pgadmin4:4.3`

`docker run -p 80:80 -e "PGADMIN_DEFAULT_EMAIL=user@domain.com" -e "PGADMIN_DEFAULT_PASSWORD=SuperSecret" -d dpage/pgadmin4:4.2`

`docker run -p 80:80 -e "PGADMIN_DEFAULT_EMAIL=user@domain.com" -e "PGADMIN_DEFAULT_PASSWORD=SuperSecret" -d dpage/pgadmin4:4.1`

`docker run -p 80:80 -e "PGADMIN_DEFAULT_EMAIL=user@domain.com" -e "PGADMIN_DEFAULT_PASSWORD=SuperSecret" -d dpage/pgadmin4:3.6`

But in the newest versions, the application doesn't perform the redirect after login (since version 4.4):
In fact, if we change the URL manually to add `/browser/` at the end instead of `login` we can access successfully to the page.

`docker run -p 80:80 -e "PGADMIN_DEFAULT_EMAIL=user@domain.com" -e "PGADMIN_DEFAULT_PASSWORD=SuperSecret" -d dpage/pgadmin4:4.4`

In this URL there is a running example with version 4.3
https://katacoda.com/gssg/scenarios/install-pgadmin-container

**Comment by dpage** [comment]
Hi

Interesting - 4.4 had a lot of dependency updates, but perhaps more relevant, it added support for being hosted behind a reverse proxy such as Nginx, in the way recommended by the Flask team (the Python framework the server is based on). I'll look into that and see if I can prove that's the issue.

However, there is something else wrong in the Dashboard tab. Your screenshot is a little messed up because of a bug in the responsive layout code, but on a wider screen I get:

Screenshot 2019-09-11 at 07 59 36

Whereas if I open it in a separate tab I get:

Screenshot 2019-09-11 at 08 00 05

Note the different menu options and lack of root node on the treeview. We've seen that issue before with similar reverse proxy issues (the ones fixed in 4.4 :-) ). 

I'll keep digging - thanks!

**Comment by dpage** [comment]
Update: It looks like there are 2 issues:

- The broken redirects are caused by the change I suspected, which was specifically there to make things work in reverse proxy situations (and it does do that in typical scenarios). The commit was: https://git.postgresql.org/gitweb/?p=pgadmin4.git;a=commit;h=f401def044c8b47974d58c71ff9e6f71f34ef41d. I'm trying to figure out what the issue is here.

- The second issue (the missing menus etc) is cause by the browsers cross-origin protection kicking in an blocking some requests (Chrome in my case). I've played with the x-frame-options configuration a little, but haven't yet got it to work.

**Comment by dpage** [comment]
Hi @gsoria. I've got caught up in some other work at the moment so one of my colleagues is looking into this. He may ask a question or two here so if you can help him out that would be awesome.

Thanks!

**Comment by dpage** [comment]
Yet another update :-). It looks like Aditya has identified the root cause of the two issues we're seeing. He's in the process of making some changes, following which we expect pgAdmin to work properly in the Katacoda environment.

**Pull request merged**
